---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - ref: manifest
      repoURL: https://github.com/corrupt952/home-apps
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.32.0
      helm:
        releaseName: argocd
        valueFiles:
        - $manifest/values/argocd.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
