---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.31.0 # renovate: depName=argoproj/argo-helm extractVersion=^argo-cd-(?<version>.+)$
    helm:
      releaseName: argocd
      parameters:
      - name: server.ingress.enabled
        value: 'true'
      - name: server.ingress.ingressClassName
        value: nginx
      - name: server.ingress.hosts[0]
        value: 'argocd.home'
      # ConfigMapのdataに設定される値のため、configs.params["server.insecure"]のような形式になる必要があるため、
      # 「.」をエスケープしてmapではなく1まとまりのKeyとして扱う
      - name: configs.params.server\.insecure
        value: 'true'
      - name: configs.params.server\.disable\.auth
        value: 'true'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
