---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: default
  source:
    chart: argo-cd-5.8.2
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: v2.5.0
    helm:
      releaseName: argo-cd
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
