---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
spec:
  project: default
  source:
    repoURL: https://github.com/corrupt952/home-apps
    targetRevision: develop/cloudflare # FIXME: branch
    path: cloudflared/base
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
