---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.3.0
    helm:
      releaseName: ingress-nginx
      parameters:
      - name: controller.service.type
        value: NodePort
      - name: controller.service.enableHttps
        value: 'false'
      - name: controller.service.nodePorts.http
        value: '32080'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
