---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: default
  sources:
    - ref: manifest
      repoURL: https://github.com/corrupt952/home-apps
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.6.0 # renovate: depName=kubernetes/ingress-nginx extractVersion=^helm-chart-(?<version>.+)$
      helm:
        releaseName: ingress-nginx
        valueFiles:
        - $manifest/values/ingress-nginx.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
