---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  project: default
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.17.0
    helm:
      releaseName: prometheus
      parameters:
      # TODO: PersistentVolumeを何らかの形で用意するまでは無効化
      - name: persistentVolumes.enabled
        value: 'false'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
