---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-games
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - ref: manifest
      repoURL: https://github.com/corrupt952/home-apps
      targetRevision: develop/wordpress # FIXME:
    - chart: wordpress
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 16.0.2
      helm:
        releaseName: wordpress
        valueFiles:
        - $manifest/values/wordpress.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wordpress-games
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
