---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - ref: manifest
      repoURL: https://github.com/corrupt952/home-apps
    - path: wordpress/base
      repoURL: https://github.com/corrupt952/home-apps
    - chart: mariadb
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 12.1.5
      helm:
        releaseName: mariadb
        valueFiles:
        - $manifest/values/mariadb.yaml
    - chart: wordpress
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 16.0.4
      helm:
        releaseName: wordpress
        valueFiles:
        - $manifest/values/wordpress.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wordpress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
